### ISSUE TITLE
SocketException : Connection refused /  SocketException : Connection reset by peer while attempting to connect to docker api on contenerized linux in GithubAction with selfhosted runner

### ISSUE THREAD

**Issue by MarcinSzyszka** [dotnet/Docker.DotNet#560]
**Output of `dotnet --info`:**
```
.NET SDK (reflecting any global.json):
 Version:   6.0.300
 Commit:   ***
Runtime Environment:
 OS Name:     ubuntu
 OS Version:  [20]***04
 OS Platform: Linux
 RID:         ubuntu.20.04-x64
 Base Path:   /home/runner/.dotnet/sdk/6.0.300/
Host (useful for support):
  Version: 6.0.5
  Commit:  70ae3df4a6
.NET SDKs installed:
  6.0.300 [/home/runner/.dotnet/sdk]
.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.5 [/home/runner/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.5 [/home/runner/.dotnet/shared/Microsoft.NETCore.App]
To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Output of `docker info`**
```
Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 0
 Server Version: 20.10.14
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: false
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3df54a852345ae[12] ***
 runc version: v1.0.3-0-gf46b6ba2
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-1073-azure
 Operating System: Alpine Linux v3.[15] *** (containerized)
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 7.771GiB
 Name: default-8sqz6-8prsb
 ID: TDD6:[23]
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: ***
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries: 1[27] ***
 Live Restore Enabled: false
 Product License: Community Engine
```

**What version of Docker.DotNet?:**

```
3.125.4
```

**Steps to reproduce the issue:**
1. Run app using Docker.DotNet in contenerized linux
2. Call one of docker api methods

**What actually happened?:**
Exception while attempting to connect to docker api on linux

```
 Error Message:
   System.Net.Http.HttpRequestException : Connection failed
---- System.Net.Sockets.SocketException : Connection refused
  Stack Trace:
     at Microsoft.Net.Http.Client.ManagedHandler.ProcessRequestAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Net.Http.Client.ManagedHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Docker.DotNet.DockerClient.PrivateMakeRequestAsync(TimeSpan timeout, HttpCompletionOption completionOption, HttpMethod method, String path, IQueryString queryString, IDictionary`2 headers, IRequestContent data, CancellationToken cancellationToken)
   at Docker.DotNet.DockerClient.PrivateMakeRequestAsync(TimeSpan timeout, HttpCompletionOption completionOption, HttpMethod method, String path, IQueryString queryString, IDictionary`2 headers, IRequestContent data, CancellationToken cancellationToken)
   at Docker.DotNet.DockerClient.MakeRequestAsync(IEnumerable`1 errorHandlers, HttpMethod method, String path, IQueryString queryString, IRequestContent body, IDictionary`2 headers, TimeSpan timeout, CancellationToken token)
   at Docker.DotNet.ContainerOperations.ListContainersAsync(ContainersListParameters parameters, CancellationToken cancellationToken)
```
another time

```
   System.Net.Http.HttpRequestException : The requested failed, see inner exception for details.
---- System.IO.IOException : Unable to read data from the transport connection: Connection reset by peer.
-------- System.Net.Sockets.SocketException : Connection reset by peer
  Stack Trace:
     at Microsoft.Net.Http.Client.HttpConnection.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Net.Http.Client.ManagedHandler.ProcessRequestAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Net.Http.Client.ManagedHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Docker.DotNet.DockerClient.PrivateMakeRequestAsync(TimeSpan timeout, HttpCompletionOption completionOption, HttpMethod method, String path, IQueryString queryString, IDictionary`2 headers, IRequestContent data, CancellationToken cancellationToken)
   at Docker.DotNet.DockerClient.PrivateMakeRequestAsync(TimeSpan timeout, HttpCompletionOption completionOption, HttpMethod method, String path, IQueryString queryString, IDictionary`2 headers, IRequestContent data, CancellationToken cancellationToken)
   at Docker.DotNet.DockerClient.MakeRequestAsync(IEnumerable`1 errorHandlers, HttpMethod method, String path, IQueryString queryString, IRequestContent body, IDictionary`2 headers, TimeSpan timeout, CancellationToken token)
   at Docker.DotNet.ContainerOperations.ListContainersAsync(ContainersListParameters parameters, CancellationToken cancellationToken)
```

**What did you expect to happen?:**
Succesfull connection and retrieve requested data

**Additional information:**
I have .net 6 application which uses Docker.Dotnet. Locally on WIN machine it works properly but when it's pushed to GithubRepo GitHub action is being executed on self hosted runner (contenerized linux) - one step of this action is `dotnet test` which uses Docker.Dotnet and it ends up with exception with stack trace added above.

Do you have any idea what went wrong or what I did wrong?

**Comment by MarcinSzyszka** [comment]
In my case docker runs with TLS so host is https://localhost:2376
